
spring:
  jpa:
    show-sql: true
  datasource:
    bak:
      jdbc-url: jdbc:postgresql://192.168.1.235:5432/nmggtkjgh
      username: gmcloud
      password: gmcloud
      driver-class-name: org.postgresql.Driver
    recode:
      jdbc-url: jdbc:postgresql://27.19.103.150:13001/nmggtkjgh
      username: gmcloud
      password: gmcloud
      driver-class-name: org.postgresql.Driver
server:
  port: 10003