
spring:
  jpa:
    show-sql: true
  datasource:
    bak:
      jdbc-url: jdbc:postgresql://192.168.1.4:5432/nmggtkjgh
      username: postgres
      password: salis
      driver-class-name: org.postgresql.Driver
    recode:
      jdbc-url: jdbc:postgresql://192.168.1.3:5432/nmggtkjgh
      username: postgres
      password: salis
      driver-class-name: org.postgresql.Driver
server:
  port: 10003